# Generated by Django 5.0.2 on 2024-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_customuserprofile_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('creator', 'Créateur'), ('advertiser', 'Annonceur'), ('association', 'Association')], max_length=14),
        ),
    ]
