# Generated by Django 5.0.2 on 2024-03-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='static/images/profile_picture.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
