# Generated by Django 5.0.2 on 2024-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_customuserprofile_campaigns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='social_links',
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='contact_mail',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Adresse e-mail'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='instagram'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='snapchat_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='snapchat'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='tiktok'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='twitch_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='twitch'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='x_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='x'),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='youtube_channel_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='youtube'),
        ),
    ]
