# Generated by Django 5.0.2 on 2024-03-14 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_customuser_managers_customuser_social_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nom')),
                ('social_links', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('main_description', models.TextField(blank=True, help_text='Enter a description for your model', null=True, verbose_name='Description')),
                ('user_description', models.TextField(blank=True, help_text='Enter a description for your model', null=True, verbose_name='Description')),
                ('partners', models.JSONField(default=dict)),
                ('campaigns', models.JSONField(default=dict)),
                ('banner', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='social_links',
        ),
    ]
