# Generated by Django 5.0.2 on 2024-03-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_customuserprofile_remove_customuser_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='user_description',
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='banner',
            field=models.ImageField(blank=True, default='images/default_banner.jpg', null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Nom'),
        ),
    ]
