# Generated by Django 5.0.2 on 2024-04-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customuserprofile_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='second_description',
            field=models.TextField(blank=True, help_text='Enter a description', null=True, verbose_name='Description'),
        ),
    ]
