# Generated by Django 5.0.2 on 2024-03-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_remove_customuserprofile_user_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserprofile',
            name='name',
        ),
    ]
