# Generated by Django 5.0.2 on 2024-05-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_customuserprofile_second_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
