# Generated by Django 5.0.2 on 2024-07-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignPayment',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='min_price',
        ),
    ]
