# Generated by Django 5.0.2 on 2024-07-19 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaigncollaboratorrequest_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='partner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'creator'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
