# Generated by Django 5.0.2 on 2024-04-27 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaigns', '0005_alter_campaign_budget_campaigncollaboratorrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, help_text='', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
