# Generated by Django 5.0.2 on 2024-04-03 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaigns', '0002_campaign_collaborater'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='collaborater',
        ),
        migrations.AddField(
            model_name='campaign',
            name='collaborator',
            field=models.ManyToManyField(related_name='campaigns_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
